server.port=8082
spring.application.name=ms-datos-org
spring.datasource.url=jdbc:postgresql://ep-lucky-cloud-ami42tlw-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RkUIf1wX4uDx
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=datos_org
spring.sql.init.mode=always
